baseURL = 'https://laboratorij-km.github.io/lab_member1/'
languageCode = 'en-us'
title = 'Member 1 Hugo Site'
theme = "member-theme"
[params]
  author = "Lab Member 1"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/" 
    weight = 1

  [[menu.main]]
    name = "Lecturing"
    url = "/lecturing/"
    weight = 2

  [[menu.main]]
    name = "Scientific work"
    url = "/cv/"
    weight = 3

  [[menu.main]]
    name = "Science and spirituality"
    url = "https://irenaroglic.si/wp-content/uploads/engbio.htm"
    weight = 4

  [[menu.main]]
    name = "Personal"
    url = "https://irenaroglic.si/wp-content/uploads/personal.pdf" 
    weight = 5

